#!/bin/sh
#PBS -W group_list=cge -A cge
#PBS -N sat_mixed_training
#PBS -e /home/projects/cge/people/malhal/nanomgt_article_results/mixed/mixed_test.err
#PBS -o /home/projects/cge/people/malhal/nanomgt_article_results/mixed/mixed_test.log
#PBS -l nodes=1:ppn=40
#PBS -l mem=128gb
#PBS -l walltime=120:00:00


# Move to the directory where you want to execute your commands
cd /home/projects/cge/people/malhal/nanomgt_article_results/mixed

# Load necessary modules
module load tools
module load miniconda3/23.5.0
conda activate mambaenv
python3 /home/projects/cge/people/malhal/NanoMGT/parameter_training/mixed_parameters_train.py


# Add additional commands here if needed
